site_name: Moil Meeting Docs
site_url: https://example.com/moil
repo_url: https://github.com/perseverance-tech-tw/video-conference-using-fisheye
repo_name: Moil Meeting

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Mode Terang
    - scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: assets/images/ui/moil_meeting_app.png
  features:
    - navigation.top      
    - search.suggest         
    - content.code.copy      


extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
plugins:
  - search

nav:
  - Home: index.md
  - Release Notes:
    - Overview: release-notes/overview.md
    - Highlights: release-notes/highlights.md
    - New Features: release-notes/new-features.md
    - Improvements: release-notes/improvements.md
    - Bug Fixes: release-notes/bug-fixes.md
  - Definition and Overview:
    - What is Moil: definition/what-is-moil.md
    - Key Features: definition/key-features.md
    - Fisheye Tech: definition/fisheye-tech.md
  - Modes:
    - Original Mode: modes/original.md
    - Discussion Mode: modes/discussion.md
    - Global Mode: modes/global.md
    - Patrol Mode: modes/patrol.md
    - Presentation Mode: modes/presentation.md
    - AI Tracking: modes/ai-tracking.md
  - Moil Meeting Installation Guide:
    - Requirements: install/requirements.md
    - User Guide: install/user-guide.md
    - Developer Guide: install/dev-guide.md
  - Moil Meeting of Usage:
    - Quick Start: usage/quick-start.md
    - Operations: usage/operations.md
    - Camera Control: usage/camera-control.md
    - Recording: usage/recording.md
  - Operations of the Moil Meeting:
    - Overview of Apps: operations/overview-of-apps.md
    - Quick Start: operations/quick-start.md
    - Start Camera: operations/start-camera.md
