site_name: Moil Meeting Docs
site_url: https://example.com/moil
repo_url: https://github.com/perseverance-tech-tw/video-conference-using-fisheye
repo_name: Moil Meeting

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - scheme: slate
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Mode Terang
    - scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: assets/images/ui/moil_meeting_app.png
  features:
    - navigation.top      
    - search.suggest         
    - content.code.copy      


extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
plugins:
  - search

nav:
  - Home: index.md
  - Release Notes:
    - Overview: release-notes/overview.md
    - Highlights: release-notes/highlights.md
    - New Features: release-notes/new-features.md
    - Improvements: release-notes/improvements.md
    - Bug Fixes: release-notes/bug-fixes.md
    - Upgrade Notes: release-notes/upgrade-notes.md
    - Getting Started: release-notes/getting-started.md
    - Changelog: release-notes/changelog.md
  - Definition and Overview:
    - What is the Moil Meeting: definition/what-is-moil.md
    - Key Features: definition/key-features.md
    - What is Fisheye Lens Technology?: definition/fisheye-tech.md
  - Modes:
    - Original Mode: modes/original.md
    - Discussion Mode: modes/discussion.md
    - Global Mode: modes/global.md
    - Patrol Mode: modes/patrol.md
    - Presentation Mode: modes/presentation.md
    - AI Tracking: modes/ai-tracking.md
  - Moil Meeting Installation Guide:
    - Operating System Requirements: install/requirements.md
    - User Installation Guide: install/user-guide.md
    - Developer Installation Guide: install/dev-guide.md
  - Moil Meeting Of Usage: usage/index.md
  - Operations of the Moil Meeting:
    - Overview of Apps: operations/overview-of-apps.md
    - Quick Start: operations/quick-start.md
    - Start Camera and Stop Camera: operations/start-camera.md
    - Start Recording and Stop Recording: operations/recording.md
    - Original Mode: operations/original-mode.md
    - Discussion Mode: operations/discussion-mode.md
    - Global Mode: operations/global-mode.md
    - Patrol Mode: operations/patrol-mode.md
    - Presentation Mode: operations/presentation-mode.md
    - Configuration Panel: operations/configuration-panel.md
